LTCOMP=/home/spectre/local/bin/lt-comp
APT=/home/spectre/local/bin/apertium-preprocess-transfer
GENMODES=/home/spectre/local/bin/apertium-gen-modes

LTCOMP=/home/spectre/svnroot/unicode-local/bin/lt-comp
APT=/home/spectre/svnroot/unicode-local/bin/apertium-preprocess-transfer
GENMODES=/home/spectre/svnroot/unicode-local/bin/apertium-gen-modes

all:
	xmllint --xinclude apertium-tg-fa.en.dix.xml > apertium-tg-fa.en.dix
	xmllint --xinclude apertium-tg-fa.tg.dix.xml > apertium-tg-fa.tg.dix
	xmllint --xinclude apertium-tg-fa.tg-fa.dix.xml > apertium-tg-fa.tg-fa.dix

	$(LTCOMP) lr apertium-tg-fa.en.dix fa-tg.automorf.bin
	$(LTCOMP) lr apertium-tg-fa.tg.dix tg-fa.automorf.bin

	$(LTCOMP) lr apertium-tg-fa.tg-fa.dix tg-fa.autobil.bin
	$(LTCOMP) rl apertium-tg-fa.tg-fa.dix fa-tg.autobil.bin

	$(LTCOMP) rl apertium-tg-fa.tg.dix fa-tg.autogen.bin
	$(LTCOMP) rl apertium-tg-fa.en.dix tg-fa.autogen.bin

	$(APT) apertium-tg-fa.tg-fa.t1x tg-fa.t1x.bin
	$(APT) apertium-tg-fa.fa-tg.t1x fa-tg.t1x.bin

	$(LTCOMP) lr apertium-tg-fa.post-en.dix tg-fa.autopgen.bin

	$(GENMODES) modes.xml

	rm apertium-tg-fa.en.dix apertium-tg-fa.tg.dix apertium-tg-fa.tg-fa.dix

clean:
	rm -rf *.bin modes
